import { IOpenAIService } from '../../domain/services/IOpenAIService';

export class MockOpenAIService implements IOpenAIService {
  private readonly MIN_DELAY_MS = 500;
  private readonly MAX_DELAY_MS = 2000;
  private readonly TOKENS_PER_RESPONSE = 150;

  private async simulateDelay(): Promise<void> {
    const delay = Math.floor(
      Math.random() * (this.MAX_DELAY_MS - this.MIN_DELAY_MS + 1) + this.MIN_DELAY_MS
    );
    return new Promise((resolve) => setTimeout(resolve, delay));
  }

  async generateResponse(question: string): Promise<{ answer: string; tokensUsed: number }> {
    // Simulate OpenAI API response time
    await this.simulateDelay();

    // Generate a mocked response based on the question
    const mockedAnswers = [
      `This is a mocked response to: "${question}". In a real implementation, this would be generated by OpenAI's API.`,
      `Based on your question "${question}", here's what I understand: This is a placeholder response for demonstration purposes.`,
      `Thank you for asking about "${question}". Here's a sample response that simulates what an AI assistant might say.`,
    ];

    const randomAnswer = mockedAnswers[Math.floor(Math.random() * mockedAnswers.length)];
    const tokensUsed = this.TOKENS_PER_RESPONSE + Math.floor(Math.random() * 50);

    return {
      answer: randomAnswer,
      tokensUsed,
    };
  }
}

